### PR TITLE
Document return codes on the manpage

### LINKED ISSUE #33: Document the exit codes in the manpage
The manpage should have a section describing the possible exit codes from the ubuntu-advantage script.

### PR DESCRIPTION
**Pull request by albertodonato**
Closes #33

### CODE REVIEW

**Comment by panlinux** [comment]
Can you add a comment that we can also exit with apt-get status codes? Currently check_result is only wrapping apt-get.

**Comment by albertodonato** [comment]
@panlinux done

**Comment by panlinux** [comment]
If apt commands run by the tool fail, the return code from apt is returned.

Suggestion:

       If apt commands run by the tool fail, the exit status from apt is returned.

+1 regardless

**Comment by albertodonato** [comment]
Good suggestion, updated

**Pull request merged**
